### ISSUE TITLE
Please, clarify the license

### ISSUE THREAD

**Issue by rkrasin** [wallarm/nascell-automl#1]
First of all, I would like to thank you for releasing this project. It's a good service to the community and is appreciated.

I have noted that at this time, the repository does not have any signs under which license the code and data are released. I recommend to add a simple top-level LICENSE file with one of the permissive licenses, such [MIT](https://opensource.org/licenses/MIT), [BSD](https://opensource.org/licenses/BSD-3-Clause) or [Apache 2](https://www.apache.org/licenses/LICENSE-2.0).

Having a license clarified, will allow more people to use the code and contribute to the project.

**Comment by mdsalnikov** [comment]
Thank you. 
We added MIT license.
