### ISSUE TITLE
cnn_dropout_rates > 1?

### ISSUE THREAD

**Issue by tornadomeet** [wallarm/nascell-automl#10]
hello @MihailSalnikov 

i print ```cnn_dropout_rates```, it always > 1, but  ```keep_prob``` in ```tf.nn.dropout()``` should between 0 and 1 , so Am i missed something?

https://github.com/wallarm/nascell-automl/blob/master/cnn.py#L40  

thanks!

**Comment by mdsalnikov** [comment]
Hello,
As far as I remember, in our experiments this value took the value 1 or more in more than 98% of cases.

**Comment by johsnows** [comment]
so is this wrong?drop out rate>1?
