### ISSUE TITLE
the net_manager.py issues like below:

### ISSUE THREAD

**Issue by wujiahongPKU** [wallarm/nascell-automl#3]
I have the question like this:the net_manager.py  why the acc-pre_acc<=0.01 return acc,acc,but else return 0.01,acc?  the first return is reward,I think if current acc is biger than pre_acc ,we should give a bigger reward if current acc is smaller than the pre_acc ,we should give a small reward.So I change the code like this:
if acc-pre_acc>=0.01:
      return acc,acc
else:
      return 0.01,acc
in this change I restart train your code ,and see the change

**Comment by dreambear1234** [comment]
Could you tell me whether your change is correct?
