### ISSUE TITLE
I found the state is [5 5 5 5 5 5 5 5] mostly，is that correct?

### ISSUE THREAD

**Issue by quweikoala** [wallarm/nascell-automl#9]
I run the code with default args，like this： python train.py
I am not sure this result is correct or not，the state stay [5 5 5 5 5 5 5 5] after episode 41. 

current time:  11:18:01.211195 episode:  0 loss:  0.8695129 last_state:  [[6 5 5 5 5 5 5 5]] last_reward:  0.01
current time:  11:19:03.559811 episode:  1 loss:  0.82795626 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9692
current time:  11:20:06.616085 episode:  2 loss:  0.8277898 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9697
current time:  11:21:09.203134 episode:  3 loss:  0.8276323 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9686
current time:  11:22:09.944140 episode:  4 loss:  0.8274824 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9695
current time:  11:23:02.033519 episode:  5 loss:  0.8273384 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9673
current time:  11:23:55.211392 episode:  6 loss:  0.82719946 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9639
current time:  11:24:47.899163 episode:  7 loss:  0.82706445 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9682
current time:  11:25:40.215955 episode:  8 loss:  0.82693106 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.96
current time:  11:26:30.442409 episode:  9 loss:  0.8268003 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9652
current time:  11:27:23.138186 episode:  10 loss:  0.82666886 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9643
current time:  11:28:15.859773 episode:  11 loss:  0.8265372 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9644
current time:  11:29:09.144128 episode:  12 loss:  0.82640415 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9666
current time:  11:30:02.121683 episode:  13 loss:  0.82626855 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9674
current time:  11:30:54.871506 episode:  14 loss:  0.8261302 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9678
current time:  11:31:47.728303 episode:  15 loss:  0.82598835 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9722
current time:  11:32:40.204606 episode:  16 loss:  0.82584196 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.968
current time:  11:33:33.027229 episode:  17 loss:  0.8256916 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9638
current time:  11:34:25.702239 episode:  18 loss:  0.82553685 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9659
current time:  11:35:18.445499 episode:  19 loss:  0.8253762 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9666
current time:  11:36:10.649878 episode:  20 loss:  0.8252096 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9672
current time:  11:37:03.511764 episode:  21 loss:  0.8250365 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9638
current time:  11:37:56.543529 episode:  22 loss:  0.8248575 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9666
current time:  11:38:48.917260 episode:  23 loss:  0.82467085 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9603
current time:  11:39:41.750848 episode:  24 loss:  0.8244784 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9668
current time:  11:40:33.872874 episode:  25 loss:  0.82427704 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9701
current time:  11:41:26.375800 episode:  26 loss:  0.8240673 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9674
current time:  11:42:20.073823 episode:  27 loss:  0.82385033 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9658
current time:  11:43:15.070581 episode:  28 loss:  0.8236259 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9663
current time:  11:44:08.731056 episode:  29 loss:  0.823393 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9654
current time:  11:45:10.557737 episode:  30 loss:  0.8231523 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9659
current time:  11:46:14.349532 episode:  31 loss:  0.8229033 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9684
current time:  11:47:17.900941 episode:  32 loss:  0.82264525 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9672
current time:  11:48:20.743621 episode:  33 loss:  0.82237947 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9694
current time:  11:49:23.948162 episode:  34 loss:  0.82210475 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9666
current time:  11:50:25.402141 episode:  35 loss:  0.8218228 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9685
current time:  11:51:27.515746 episode:  36 loss:  0.8215324 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9665
current time:  11:52:31.024672 episode:  37 loss:  0.82123476 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9645
current time:  11:53:32.615467 episode:  38 loss:  0.82093036 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9676
current time:  11:54:34.280382 episode:  39 loss:  0.82061756 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9696
current time:  11:55:36.424899 episode:  40 loss:  0.82029724 last_state:  [[4 5 5 5 5 5 5 5]] last_reward:  0.9668
current time:  11:56:37.860668 episode:  41 loss:  0.8414872 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9698
current time:  11:57:35.049458 episode:  42 loss:  0.8410128 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9644
current time:  11:58:28.113677 episode:  43 loss:  0.8406736 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9659
current time:  11:59:29.199719 episode:  44 loss:  0.84033144 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.97
current time:  12:00:30.038286 episode:  45 loss:  0.83998317 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.968
current time:  12:01:30.826825 episode:  46 loss:  0.83963203 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.967
current time:  12:02:32.037496 episode:  47 loss:  0.83927834 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9638
current time:  12:03:32.856483 episode:  48 loss:  0.8389237 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9691
current time:  12:04:34.652328 episode:  49 loss:  0.8385659 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9655
current time:  12:05:35.969136 episode:  50 loss:  0.8382091 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9678
current time:  12:06:36.949402 episode:  51 loss:  0.83785236 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9631
current time:  12:07:37.401473 episode:  52 loss:  0.837499 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9691
current time:  12:08:38.954820 episode:  53 loss:  0.83714634 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9676
current time:  12:09:40.710657 episode:  54 loss:  0.83679837 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9663
current time:  12:10:42.550953 episode:  55 loss:  0.83645606 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9693
current time:  12:11:36.616196 episode:  56 loss:  0.8361192 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9693
current time:  12:12:28.967176 episode:  57 loss:  0.83579 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.967
current time:  12:13:21.472742 episode:  58 loss:  0.8354703 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9675
current time:  12:14:14.743933 episode:  59 loss:  0.83516043 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9676
current time:  12:15:07.605319 episode:  60 loss:  0.83486146 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9667
current time:  12:16:24.680310 episode:  61 loss:  0.8345748 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9691
current time:  12:17:41.622057 episode:  62 loss:  0.83430046 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9634
current time:  12:18:58.016953 episode:  63 loss:  0.8340415 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9632
current time:  12:20:13.264490 episode:  64 loss:  0.83379686 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9687
current time:  12:21:28.810527 episode:  65 loss:  0.833566 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9693
current time:  12:22:45.991525 episode:  66 loss:  0.83335066 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9697
current time:  12:24:00.959656 episode:  67 loss:  0.8331513 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9668
current time:  12:25:17.480776 episode:  68 loss:  0.8329686 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9651
current time:  12:26:34.055509 episode:  69 loss:  0.8328022 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9695
current time:  12:27:35.784811 episode:  70 loss:  0.83265096 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9649
current time:  12:28:30.272217 episode:  71 loss:  0.83251595 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9662
current time:  12:29:22.834470 episode:  72 loss:  0.83239573 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9661
current time:  12:30:34.972866 episode:  73 loss:  0.8322899 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9666
current time:  12:31:53.158066 episode:  74 loss:  0.8321976 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9653
current time:  12:33:09.588201 episode:  75 loss:  0.8321181 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9653
current time:  12:34:25.893570 episode:  76 loss:  0.8320503 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9644
current time:  12:35:43.238231 episode:  77 loss:  0.83199334 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9671
current time:  12:36:59.291973 episode:  78 loss:  0.8319458 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9671
current time:  12:38:15.981345 episode:  79 loss:  0.8319068 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9675
current time:  12:39:33.109462 episode:  80 loss:  0.83187526 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9692
current time:  12:40:48.522003 episode:  81 loss:  0.8318501 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9681
current time:  12:41:48.327012 episode:  82 loss:  0.8318305 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.962
current time:  12:42:44.437649 episode:  83 loss:  0.8318155 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9687
current time:  12:43:36.731452 episode:  84 loss:  0.8318041 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9674
current time:  12:44:30.064186 episode:  85 loss:  0.83179563 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9654
current time:  12:45:22.897285 episode:  86 loss:  0.83178955 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9681
current time:  12:46:14.180168 episode:  87 loss:  0.8317852 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9667
current time:  12:47:06.337785 episode:  88 loss:  0.83178216 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9691
current time:  12:47:58.450676 episode:  89 loss:  0.83178014 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9691
current time:  12:48:50.051810 episode:  90 loss:  0.8317788 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9676
current time:  12:49:42.499442 episode:  91 loss:  0.831778 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9675
current time:  12:50:34.631609 episode:  92 loss:  0.83177745 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9672
current time:  12:51:26.977310 episode:  93 loss:  0.8317771 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9702
current time:  12:52:19.798771 episode:  94 loss:  0.8317769 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9645
current time:  12:53:12.668945 episode:  95 loss:  0.83177686 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9663
current time:  12:54:05.104380 episode:  96 loss:  0.8317768 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9701
current time:  12:54:56.696553 episode:  97 loss:  0.83177674 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9713
current time:  12:55:49.427225 episode:  98 loss:  0.83177674 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9673
current time:  12:56:42.010306 episode:  99 loss:  0.83177674 last_state:  [[5 5 5 5 5 5 5 5]] last_reward:  0.9646

**Comment by mdsalnikov** [comment]
Hello. This may be correct in terms of the script, but not best state. Unfortunately due to the random initialization, sometimes you can see not the best results. Contributions are welcome!
